version: '3'

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD= p4ssw0rd
      MYSQL_USER= user
      MYSQL_PASSWORD= p4ssw0rd
      MYSQL_DATABASE= filerun
    volumes:
      - ./db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST= db
      FR_DB_PORT= 3306
      FR_DB_NAME= filerun
      FR_DB_USER= user
      FR_DB_PASS= p4ssw0rd
      APACHE_RUN_USER= www-data
      APACHE_RUN_USER_ID= 33
      APACHE_RUN_GROUP= www-data
      APACHE_RUN_GROUP_ID= 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8200:80"
    volumes:
      - ./html:/var/www/html
      - ./user-files:/user-files
       
